### PR TITLE
Pre - Release 25 (WIP)

### PR DESCRIPTION
**Pull request by TeamSpen210**
* Make the Splash Screen non-modal (now it can be movable with the mouse).
* Fix Glass/Grating item getting surface sounds mixed up.
* Ensure fancy rendering is used on the largest goo pit in the map.
* Fix BEEmod/BEE2-items#1448, Turrets not shooting Wheatley Monitors.
* Fix missing env_cubemaps in 70´s and P1 CO-OP Styles (#284).
* Style Properties can now be used to configure items as well.

### CODE REVIEW

**Comment by M0LD** [comment]
How do "me" Add This "Wip" Content to The BEE 2 Software???

**Comment by IratePirate** [comment]
@M0LD Go to the main code screen, select "branch" and go to "dev". Then go to the green button that says "clone or download".

**Comment by Luke18033** [comment]
@M0LD @IratePirate Nope, don't do that. There are instructions in the README to do it properly.

**Comment by ZFM2004** [comment]
Add ALL OFFICE items
add Thinking with time machines mod items & textures.
add a paint gun fizzler you can just put down (paintgun wont work 4 me)
add cake
add turret costumes
add all RATMAN items (including portal & portal 2)
add rest of doors
add breakable glass
add more observation rooms ( e.x. : Curved)
add observation rooms you can portal into and do a WHOLE other part of the map
add bombs
add a way to change loading screen when you play the level
add a scroll bar (if you can)
add furniture
add a way to make things able to be picked up
add a way to change if you have a portal gun or a paingun or a portal/paintgun with the TWTM time machine or no portal device
add way to end game where you want it to
add a way to test outside of aperture
add a way to change display on the screen (to glados or wheatley)
add ALL BEDS
add wall-climbing gel (the gel that lets you climb on walls, the one that made people sick)
THANK YOU!

**Comment by ZFM2004** [comment]
Also, please allow a mode to make a sandbox (lets you pick all textures)
add posters
add ways to make pits
Once again
My top wishes are
ALL PORTAL & PORTAL 2
Furniture
Posters
Ratman items
office items
extended relaxation vault items
all doors
OTHER STUFF ON LIST
breakable glass into observation rooms
breakable glass
scrollable item inventory
TWTM stuff
ways to switch the time machine (TWTM), The portal device (P2), & the Paintgun (aperture tag) on & off
add a already-made paingun fizzler (one for beginning & one for end)
Observation rooms you can portal / bounce into & be able to open the door there & continue to a corridor & we can make a adventure that way
Pick the loading screen
THXX

**Comment by Luke18033** [comment]
Most of those have already been suggested.

**Comment by ZFM2004** [comment]
I agree completely with you, I only say that because of the fact that I want to make sure the ideas are out there! I am glad to have people like you on the internet because of the fact that you guys are smart enough to say your opinion / comment without hesitation of a remark. thank you for you comment, seriously. 

                                                      -ZFM2004

**Comment by ZFM2004** [comment]
once again I only list these as my requests so I completely agree except the fact that I am just saying what I want. Your statement is EXTREMELY important & logical! 😄

**Comment by TeamSpen210** [comment]
This also isn't a place for suggestions, make an issue for that.

**Pull request merged**
