### PR TITLE
Smoother images

### PR DESCRIPTION
**Pull request by HugoBDesigner**
I know this is probably nitpicking but some of the images (loading
screen and logo) were too sharp for my eyes

### CODE REVIEW

**Comment by TeamSpen210** [comment]
Why did you downscale the screenshots?

**Comment by HugoBDesigner** [comment]
The full res screenshots were scaled down via code, which isn't the smoothest way of doing that. I used a better downscale smoothing via Photoshop.
Uuuuunless the window size for the loading screen varies for each computer, in which case... I guess only the logo could be salvaged

**Comment by TeamSpen210** [comment]
The size does indeed.

**Comment by HugoBDesigner** [comment]
Sorry about that, I'll undo the image resizing.

**Comment by TeamSpen210** [comment]
Feel free to commit the logo change directly to dev.

**Pull request closed without merging**
